version: '3.7'
services:
  compute:
    image: gurobi/compute:13.0.1
    restart: always
    ports:
      - "61000:61000"
    command: --hostname=localhost
    volumes:
      - ./gurobi.lic:/opt/gurobi/gurobi.lic:ro